### ISSUE TITLE
Message Passed and in return getting empty value

### ISSUE THREAD

**Issue by DineshGuptaa** [hhkbp2/go-logging#10]
Hi ,
I am working on Windows 10 and Go 1.9.
I am running sample provide in the document and nothing get printed in the file as well as not in console.
logger.go,record.go------file
	record := NewLogRecord(
		self.name,
		level,
		callerInfo.PathName,
		callerInfo.FileName,
		callerInfo.LineNo,
		callerInfo.FuncName,
		format,
		true,
		args) //Here I can see the value line no 380
	self.Handle(record) // args value in empty ""

**Comment by hhkbp2** [comment]
Hi @DineshGuptaa ,

Example 1 works fine to print message to standard output. But there is a bug in the constructor of `RotatingFileHandler`, which forgets to register itself to `Closer`. This bug is fixed at the latest code, in this commit

https://github.com/hhkbp2/go-logging/commit/377ba05d98977baa2a0d9e13f13aac2f3a47ac4d

All examples are tested ok after updating the latest code in windows OS. Please retry to run these examples.

**Comment by DineshGuptaa** [comment]
Thanks for quick reply & fixing the issue. Its working fine.
