### ISSUE TITLE
dateFormat defaulting to defaultDateFormat instead of datefmt from config.yml file

### ISSUE THREAD

**Issue by aishwaryaprabhat** [hhkbp2/go-logging#20]
To reproduce, you can run the config file example and try changing the datefmt in the config.yml file

P.S. love the package! Thank you for your hard work :)

**Comment by hhkbp2** [comment]
This issue is fixed at #15 

I guess the problem is that the go module will download the last tag revision v0.3.0 by default. At that tag revision, the issue was not fixed yet. It should fix it to specify the latest revision in master branch using command

```shell
go get github.com/hhkbp2/go-logging@master
```

Anyway I will make a new tag so that it will work without specifying the master branch.

Thanks!
