### ISSUE TITLE
Add Reopen() function (required for log rotating)

### ISSUE THREAD

**Issue by zamotivator** [hhkbp2/go-logging#4]
We need function Reopen() which close and reopen all file handlers.
It's required for SIGHUP processing (log rotate)

**Comment by hhkbp2** [comment]
Hi @zamotivator ,

I don't get the point why you need `SIGHUP` to rotate logs, since there already exists some file handlers as `TimedRotatingFileHandler`, `RotatingFileHandler`, which handle log rotating in the first place.  The usal way to use logging facility is to initialize once, and shutdown everything before exiting the whole program. 

Anyway if you really need to close all handlers and reopen them, it's possible to do that by calling `Shutdown()` and then some configuration fucntion(or `ApplyXXXConfigFile()`) to re-initialize everything, e.g. loggers, handlers, formatters.

**Comment by zamotivator** [comment]
So, what would be with logger calls between Shutdown() and ApplyConfig()?
Will lost records?

**Comment by hhkbp2** [comment]
@zamotivator `Shutdown()` will close all handlers, which means no log message would be handled(because all handlers are closed). Closing any specified handler manually is similar. Logically, if we close a file, it could not be written before we re-open it. To restrict the access to this critical section, we could use Mutex/Lock for synchronization, if log messages are not allowed to be lost. But it seems not a good idea to use Mutex/Lock to wrap `go-logging` interfaces outside.

Could you please clarify in detail what kind of rotate/reconfiguration needs to be done in you task? I need to know the requirement in detail before a good solution comes out.

**Comment by hhkbp2** [comment]
There is no update on this issue over 2 months. I assume the problem was solved and close this issue now.

**Comment by zamotivator** [comment]
Yes, we do not use go-logging anymore
